/*
 * generated by Xtext
 */
package co.edu.unal.modev.business.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BusinessDslUiModule extends co.edu.unal.modev.business.ui.AbstractBusinessDslUiModule {
	public BusinessDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
