/*
 * generated by Xtext
 */
package co.edu.unal.modev.repository.ui.contentassist

import co.edu.unal.modev.repository.ui.contentassist.AbstractRepositoryDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RepositoryDslProposalProvider extends AbstractRepositoryDslProposalProvider {
}
