/*
 * generated by Xtext
 */
package co.edu.unal.modev.mongoConfig.ui.contentassist

import co.edu.unal.modev.mongoConfig.ui.contentassist.AbstractMongoConfigDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MongoConfigDslProposalProvider extends AbstractMongoConfigDslProposalProvider {
}
