/*
 * generated by Xtext
 */
package co.edu.unal.modev.route.ui.contentassist

import co.edu.unal.modev.route.ui.contentassist.AbstractRouteDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RouteDslProposalProvider extends AbstractRouteDslProposalProvider {
}
