/*
 * generated by Xtext
 */
package co.edu.unal.modev.entity;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityDslRuntimeModule extends co.edu.unal.modev.entity.AbstractEntityDslRuntimeModule {

}
