/*
* generated by Xtext
*/
package co.edu.unal.modev.dbConfig;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DbConfigDslStandaloneSetup extends DbConfigDslStandaloneSetupGenerated{

	public static void doSetup() {
		new DbConfigDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

