/*
 * generated by Xtext
 */
package co.edu.unal.modev.documentRepository.ui.contentassist

import co.edu.unal.modev.documentRepository.ui.contentassist.AbstractDocumentRepositoryDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DocumentRepositoryDslProposalProvider extends AbstractDocumentRepositoryDslProposalProvider {
}
