/*
 * generated by Xtext
 */
package co.edu.unal.modev.dtoFromDocument;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DtoFromDocumentDslRuntimeModule extends co.edu.unal.modev.dtoFromDocument.AbstractDtoFromDocumentDslRuntimeModule {

}
