/*
 * generated by Xtext
 */
package co.edu.unal.modev.document.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DocumentDslUiModule extends co.edu.unal.modev.document.ui.AbstractDocumentDslUiModule {
	public DocumentDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
