/*
* generated by Xtext
*/
package co.edu.unal.modev.business;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BusinessDslStandaloneSetup extends BusinessDslStandaloneSetupGenerated{

	public static void doSetup() {
		new BusinessDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

