/*
 * generated by Xtext
 */
package co.edu.unal.modev.business;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BusinessDslRuntimeModule extends co.edu.unal.modev.business.AbstractBusinessDslRuntimeModule {

}
