/*
 * generated by Xtext
 */
package co.edu.unal.modev.layeredApp;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LayeredAppDslRuntimeModule extends co.edu.unal.modev.layeredApp.AbstractLayeredAppDslRuntimeModule {
	
	
}
