/*
* generated by Xtext
*/
package co.edu.unal.modev.layeredApp;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LayeredAppDslStandaloneSetup extends LayeredAppDslStandaloneSetupGenerated{

	public static void doSetup() {
		new LayeredAppDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

