/*
 * generated by Xtext
 */
package co.edu.unal.modev.repository.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RepositoryDslUiModule extends co.edu.unal.modev.repository.ui.AbstractRepositoryDslUiModule {
	public RepositoryDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
