/*
 * generated by Xtext
 */
package co.edu.unal.modev.dbConfig.ui.contentassist

import co.edu.unal.modev.dbConfig.ui.contentassist.AbstractDbConfigDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DbConfigDslProposalProvider extends AbstractDbConfigDslProposalProvider {
}
