/*
 * generated by Xtext
 */
package co.edu.unal.modev.dto.ui.contentassist

import co.edu.unal.modev.dto.ui.contentassist.AbstractDtoDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DtoDslProposalProvider extends AbstractDtoDslProposalProvider {
}
