/*
* generated by Xtext
*/
package co.edu.unal.modev.route;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RouteDslStandaloneSetup extends RouteDslStandaloneSetupGenerated{

	public static void doSetup() {
		new RouteDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

