/*
 * generated by Xtext
 */
package co.edu.unal.modev.route;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RouteDslRuntimeModule extends co.edu.unal.modev.route.AbstractRouteDslRuntimeModule {

}
