/*
 * generated by Xtext
 */
package co.edu.unal.modev.documentRepository.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DocumentRepositoryDslUiModule extends co.edu.unal.modev.documentRepository.ui.AbstractDocumentRepositoryDslUiModule {
	public DocumentRepositoryDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
