/*
 * generated by Xtext
 */
package co.edu.unal.modev.mongoConfig.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MongoConfigDslUiModule extends co.edu.unal.modev.mongoConfig.ui.AbstractMongoConfigDslUiModule {
	public MongoConfigDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
