/*
 * generated by Xtext
 */
package co.edu.unal.modev.dtoFromDocument.scoping

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
class DtoFromDocumentDslScopeProvider extends co.edu.unal.modev.dto.scoping.DtoDslScopeProvider {

}
