/*
 * generated by Xtext
 */
package co.edu.unal.modev.entity.ui.contentassist

import co.edu.unal.modev.entity.ui.contentassist.AbstractEntityDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EntityDslProposalProvider extends AbstractEntityDslProposalProvider {
}
