/*
 * generated by Xtext
 */
package co.edu.unal.modev.entity.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EntityDslUiModule extends co.edu.unal.modev.entity.ui.AbstractEntityDslUiModule {
	public EntityDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
