/*
 * generated by Xtext
 */
package co.edu.unal.modev.relationalRepository.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RelationalRepositoryDslUiModule extends co.edu.unal.modev.relationalRepository.ui.AbstractRelationalRepositoryDslUiModule {
	public RelationalRepositoryDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
