/*
 * generated by Xtext
 */
package co.edu.unal.modev.document.ui.contentassist

import co.edu.unal.modev.document.ui.contentassist.AbstractDocumentDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DocumentDslProposalProvider extends AbstractDocumentDslProposalProvider {
}
