/*
 * generated by Xtext
 */
package co.edu.unal.modev.mongoConfig;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MongoConfigDslRuntimeModule extends co.edu.unal.modev.mongoConfig.AbstractMongoConfigDslRuntimeModule {

}
