/*
* generated by Xtext
*/
package co.edu.unal.modev.mongoConfig;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MongoConfigDslStandaloneSetup extends MongoConfigDslStandaloneSetupGenerated{

	public static void doSetup() {
		new MongoConfigDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

