/*
* generated by Xtext
*/
package co.edu.unal.modev.documentRepository;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DocumentRepositoryDslStandaloneSetup extends DocumentRepositoryDslStandaloneSetupGenerated{

	public static void doSetup() {
		new DocumentRepositoryDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

