/*
 * generated by Xtext
 */
package co.edu.unal.modev.dbConfig.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DbConfigDslUiModule extends co.edu.unal.modev.dbConfig.ui.AbstractDbConfigDslUiModule {
	public DbConfigDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
