/*
* generated by Xtext
*/
package co.edu.unal.modev.dto;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DtoDslStandaloneSetup extends DtoDslStandaloneSetupGenerated{

	public static void doSetup() {
		new DtoDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

