/*
 * generated by Xtext
 */
package co.edu.unal.modev.dto;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DtoDslRuntimeModule extends co.edu.unal.modev.dto.AbstractDtoDslRuntimeModule {

}
