/*
 * generated by Xtext
 */
package co.edu.unal.modev.document;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DocumentDslRuntimeModule extends co.edu.unal.modev.document.AbstractDocumentDslRuntimeModule {

}
