/*
 * generated by Xtext
 */
package co.edu.unal.modev.layeredApp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LayeredAppDslUiModule extends co.edu.unal.modev.layeredApp.ui.AbstractLayeredAppDslUiModule {
	public LayeredAppDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
