/*
 * generated by Xtext
 */
package co.edu.unal.modev.dtoFromDocument.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DtoFromDocumentDslUiModule extends co.edu.unal.modev.dtoFromDocument.ui.AbstractDtoFromDocumentDslUiModule {
	public DtoFromDocumentDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
