/*
 * generated by Xtext
 */
package co.edu.unal.modev.layeredApp.ui.contentassist

import co.edu.unal.modev.layeredApp.ui.contentassist.AbstractLayeredAppDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LayeredAppDslProposalProvider extends AbstractLayeredAppDslProposalProvider {
}
