/*
 * generated by Xtext
 */
package co.edu.unal.modev.business.ui.contentassist

import co.edu.unal.modev.business.ui.contentassist.AbstractBusinessDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class BusinessDslProposalProvider extends AbstractBusinessDslProposalProvider {
}
