/*
* generated by Xtext
*/
package co.edu.unal.modev.relationalRepository;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RelationalRepositoryDslStandaloneSetup extends RelationalRepositoryDslStandaloneSetupGenerated{

	public static void doSetup() {
		new RelationalRepositoryDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

