/*
 * generated by Xtext
 */
package co.edu.unal.modev.relationalRepository;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RelationalRepositoryDslRuntimeModule extends co.edu.unal.modev.relationalRepository.AbstractRelationalRepositoryDslRuntimeModule {

}
