/*
 * generated by Xtext
 */
package co.edu.unal.modev.dtoFromDocument.ui.contentassist

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DtoFromDocumentDslProposalProvider extends AbstractDtoFromDocumentDslProposalProvider {
	
}
