/*
 * generated by Xtext
 */
package co.edu.unal.modev.route.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RouteDslUiModule extends co.edu.unal.modev.route.ui.AbstractRouteDslUiModule {
	public RouteDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
