/*
* generated by Xtext
*/
package co.edu.unal.modev.repository;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RepositoryDslStandaloneSetup extends RepositoryDslStandaloneSetupGenerated{

	public static void doSetup() {
		new RepositoryDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

