/*
 * generated by Xtext
 */
package co.edu.unal.modev.relationalRepository.ui.contentassist

import co.edu.unal.modev.relationalRepository.ui.contentassist.AbstractRelationalRepositoryDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RelationalRepositoryDslProposalProvider extends AbstractRelationalRepositoryDslProposalProvider {
}
