/*
 * generated by Xtext
 */
package co.edu.unal.modev.dto.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DtoDslUiModule extends co.edu.unal.modev.dto.ui.AbstractDtoDslUiModule {
	public DtoDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
